name: dropdown_banner
description: Manages the creation and animation of banner ui elements that are useful for displaying warnings and updates to users.
version: 1.3.0
homepage: https://github.com/flyrboy96/flutter_dropdown_banner
author: Bruce Brookshire <bruce.t.brookshire@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_notification_center: ^1.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
